[package]
name = "execgraph"
version = "0.1.0"
authors = ["Robert T. McGibbon <rmcgibbo@gmail.com>"]
edition = "2018"
resolver = "2"

[lib]
name = "execgraph"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "execgraph-bench"
required-features = ["coz"]

[profile.release]
debug = 1
incremental = true
lto = "off"

[dependencies]
advisory-lock = "0.3.0"
aho-corasick = "0.7.19"
anyhow = "1.0.65"
async-channel = "1.7.1"
async-priority-channel = "0.1.0"
axum = { version = "0.5.16", features = ["json"] }
atty = "0.2.14"
bitvec = "1.0.1"
clap = { version = "3.2.22", features = ["derive"] }
coz = { version = "0.1.3", optional = true }
dashmap = "5.4.0"
derivative = "2.2.0"
event-listener = "2.5.3"
futures = "0.3.24"
gethostname = "0.2.3"
grep-cli = "0.1.6"
hyper = "0.14.20"
lazy_static = "1.4.0"
libc = "0.2.133"
lzzzz = "1.0.3"
notify = "5.0.0"
osstrtools = "0.2.2"
postcard = { version = "1.0.2", features = ["use-std"], default-features = false }
petgraph = { version = "0.6.2", features = ["graphmap"], default-features = false }
pyo3 = { version = "0.17.1", optional = true }
pythonize = { version = "0.17.0", optional = true }
quantiles = "0.7.1"
rand = "0.8.5"
regex = "1.6.0"
reqwest = { version = "0.11.12", default-features = false }
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
shell-words = "1.1.0"
slotmap = "1.0.6"
termcolor = "1.1.3"
thiserror = "1.0.35"
tokio = { version = "1.21.1", features = ["full", "tracing"] }
tokio-command-fds = "0.2.1"
tokio-pipe = "0.2.12"
tokio-util = "0.7.4"
tower = "0.4.13"
tower-http = { version = "0.3.4", features = ["trace", "add-extension"] }
tracing = "0.1.36"
# tracing-appender = "0.2.2"
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
url = "2.3.1"
whoami = "1.2.3"

# https://pyo3.rs/v0.11.1/faq.html#i-cant-run-cargo-test-im-having-linker-issues-like-symbol-not-found-or-undefined-reference-to-_pyexc_systemerror
# to run rust tests, need to do ``$ cargo test --no-default-features``
[features]
python = [ "pyo3/extension-module", "pyo3", "pythonize" ]
default = [ "python" ]
cozprof = [ "coz" ]
