[package]
name = "execgraph"
version = "0.1.0"
authors = ["Robert T. McGibbon <rmcgibbo@gmail.com>"]
edition = "2018"
resolver = "2"

[lib]
name = "execgraph"
crate-type = ["cdylib", "rlib"]

[profile.release]
debug = 1
incremental = true
lto = "off"

[dependencies]
advisory-lock = "^0.3"
anyhow = "^1.0"
async-channel = "1.6.1"
async-priority-channel = "0.1"
bincode = "^1"
console-subscriber = "*"
crc32fast = "^1"
derivative = "2.2.0"
env_logger = "^0.9"
futures = "^0.3"
gethostname = "^0.2"
hyper = "^0.14"
log = "^0.4"
nix = "^0.22"
num_cpus = "^1"
petgraph = { version = "^0.6", features = ["graphmap"], default-features = false }
pyo3 = "^0.14"
pythonize = "^0.14"
rand = "^0.8"
reqwest = { version = "0.11", features = ["json"],  default-features = false }
routerify = "^2"
routerify-json-response = "^2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "^1", features = ["full", "tracing"] }
tokio-util = {version = "0.6.8"}
structopt = { version = "0.3", default-features = false }
thiserror = "^1"
url = "^2"
whoami = "^1"
tracing = "^0.1"
tracing-subscriber = "^0.3"

# https://pyo3.rs/v0.11.1/faq.html#i-cant-run-cargo-test-im-having-linker-issues-like-symbol-not-found-or-undefined-reference-to-_pyexc_systemerror
# to run rust tests, need to do ``$ cargo test --no-default-features``
[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]
