name: "Test"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  x86-64:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3.1.0
    - uses: cachix/install-nix-action@v17
    - uses: cachix/cachix-action@v12
      with:
        name: wrk
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        pushFilter: "(-source$|nixpkgs.tar.gz$)"
    - name: Build
      run: |
        nix build -L
        nix flake check -L
